name: Generate Rust Docs and Publish to Wiki

on:
  push:
    branches:
      - main # or master, depending on your main branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to push to the wiki

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Generate documentation
        run: cargo doc

      - name: Publish documentation to Wiki
        uses: actions-rs/cargo-doc-sync@v0.1
        with:
          branch: gh-pages # This is the branch where the docs will be published. GitHub's wiki uses a separate repo, often served by a branch like gh-pages.
          message: "Auto-generate and publish Rust documentation"
