name: Fuzz Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1' # optional weekly run

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz --version ^0.12
      - name: Build fuzz targets
        run: |
          cd fuzz
          cargo fuzz build
      - name: Run fuzz smoke (filter parser)
        run: |
          cd fuzz
          cargo fuzz run fuzz_filter_parser -- -runs=2000 -timeout=5
      - name: Run fuzz smoke (update parser)
        run: |
          cd fuzz
          cargo fuzz run fuzz_update_parser -- -runs=2000 -timeout=5
