name: Miri (UB checker)

on:
  schedule:
    - cron: '0 5 * * 1' # Weekly Monday
  workflow_dispatch:

jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-miri-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Miri
        run: |
          rustup component add miri
          cargo miri setup
      - name: Run tests under Miri
        env:
          MIRIFLAGS: "-Zmiri-strict-provenance"
        run: |
          cargo miri test --workspace --all-features