name: Mutation testing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # Weekly, Mondays at 03:00 UTC

jobs:
  cargo-mutants:
    name: Run cargo-mutants
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-mutants
        run: cargo install cargo-mutants

      - name: Run mutation tests
        run: cargo mutants -v